import { z } from "zod";

export const serverEnvSchema = z.object({
  APP_ENV: z.enum(["local", "development", "staging", "production"]).default("local"),
  DATABASE_URL: z.string().url(),
  REDIS_URL: z.string().url(),
  RABBITMQ_URL: z.string().url(),
  QDRANT_URL: z.string().url(),
  QDRANT_MEMORY_COLLECTION: z.string().min(1).default("faios_memory"),
  MEMORY_EMBEDDING_PROVIDER: z.enum(["auto", "openai", "deterministic"]).default("auto"),
  MEMORY_EMBEDDING_DIMENSIONS: z.coerce.number().int().positive().default(1536),
  MEMORY_VECTOR_SYNC_MODE: z.enum(["async", "disabled"]).default("async"),
  MEMORY_VECTOR_JOB_DISPATCH_ENABLED: z.coerce.boolean().default(false),
  MEMORY_VECTOR_QUEUE_NAME: z.string().min(1).default("faios.memory.vector-sync"),
  MEMORY_VECTOR_DEAD_LETTER_QUEUE_NAME: z.string().min(1).default("faios.memory.vector-sync.dlq"),
  MEMORY_VECTOR_WORKER_CONCURRENCY: z.coerce.number().int().min(1).max(100).default(4),
  MEMORY_VECTOR_JOB_MAX_ATTEMPTS: z.coerce.number().int().positive().default(5),
  MEMORY_VECTOR_RETRY_BASE_DELAY_MS: z.coerce.number().int().positive().default(1000),
  MEMORY_VECTOR_RETRY_MAX_DELAY_MS: z.coerce.number().int().positive().default(60000),
  WORKER_RABBITMQ_CONSUMER_ENABLED: z.coerce.boolean().default(false),
  WORKER_EXECUTION_LOOP_ENABLED: z.coerce.boolean().default(false),
  WORKER_EXECUTION_POLL_INTERVAL_MS: z.coerce.number().int().min(100).max(300000).default(5000),
  WORKER_EXECUTION_CONCURRENCY: z.coerce.number().int().min(1).max(100).default(1),
  WORKER_MEMORY_VECTOR_RABBITMQ_CONSUMER_ENABLED: z.coerce.boolean().default(false),
  WORKER_MEMORY_VECTOR_LOOP_ENABLED: z.coerce.boolean().default(false),
  WORKER_MEMORY_VECTOR_POLL_INTERVAL_MS: z.coerce.number().int().min(100).max(300000).default(5000),
  WORKER_METRICS_PORT: z.coerce.number().int().positive().optional(),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_API_BASE_URL: z.string().url().default("https://api.openai.com/v1"),
  OPENAI_EMBEDDING_MODEL: z.string().min(1).default("text-embedding-3-small"),
  CORS_ALLOWED_ORIGINS: z.string().optional(),
  BUSINESS_API_RATE_LIMIT_ENABLED: z.coerce.boolean().default(true),
  BUSINESS_API_RATE_LIMIT_WINDOW_MS: z.coerce.number().int().positive().default(60000),
  BUSINESS_API_RATE_LIMIT_MAX_REQUESTS: z.coerce.number().int().positive().default(300),
  BUSINESS_API_COMMAND_RATE_LIMIT_WINDOW_MS: z.coerce.number().int().positive().default(60000),
  BUSINESS_API_COMMAND_RATE_LIMIT_MAX_REQUESTS: z.coerce.number().int().positive().default(20),
  FAIOS_TRACING_ENABLED: z.coerce.boolean().default(false),
  FAIOS_SERVICE_NAME: z.string().min(1).optional(),
  OTEL_EXPORTER_OTLP_ENDPOINT: z.string().url().optional(),
});

export type ServerEnv = z.infer<typeof serverEnvSchema>;
